apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}
  labels: {{- include "myapp.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.app.port | quote }}
  DB_HOST: {{ include "myapp.fullname" . }}-mysql
  DB_PORT: "3306"
  DB_NAME: {{ .Values.db.name | quote }}
  