{{- if .Values.externalSecrets.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalSecrets.serviceAccountName }}
  labels: {{- include "myapp.labels" . | nindent 4 }}
{{- end }}
