{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "myapp.fullname" . }}-vault
  labels: {{- include "myapp.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.externalSecrets.vaultAddress | quote }}
      path: secret              # the KV mount
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Values.externalSecrets.vaultRole }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccountName }}
{{- end }}
